[project]
name = "flash-attention-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "triton>=3.5.0",
]
